
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DATATYPE ID SEMICOLON\n    data_type_declaration : DATATYPE ID SEMICOLON\n    empty :'
    
_lr_action_items = {'DATATYPE':([0,],[2,]),'$end':([1,4,],[0,-1,]),'ID':([2,],[3,]),'SEMICOLON':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'data_type_declaration':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> data_type_declaration","S'",1,None,None,None),
  ('data_type_declaration -> DATATYPE ID SEMICOLON','data_type_declaration',3,'p_data_type_declaration','yacc.py',15),
  ('empty -> <empty>','empty',0,'p_empty','yacc.py',21),
]
